basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

handler404 = "account.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.basket_view, name='basket_view'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('error/', views.error_view, name='error'),
    path('webhook/', views.stripe_webhook),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_product'),
    path('store/about', views.about, name='about'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/', views.shop_product, name='shop')
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/defaults.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

store/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    text = forms.CharField(label="Enter Comment", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'text', 'id': 'form-comment'}))

    class Meta:
        model = Comment
        fields = ['text']

basket/views.py
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        serialized_queryset = serializers.serialize('python', [product, ])

        basket.add(product=product, qty=product_qty)
        return JsonResponse(serialized_queryset, safe=False)


def basket_update(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        basketsubtotal = basket.get_subtotal_price()
        producttotal = basket.get_price(product=product_id)
        response = JsonResponse({'qty': basketqty, 'subtotal': basketsubtotal, 'ptotal': producttotal})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_subtotal_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

store/views.py
from django.core import serializers
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render

from .forms import CommentForm
from .models import Category, Product


def about(request):
    return render(request, 'store/about.html')


def all_products(request):
    # Toggle product
    if request.method == "POST":
        product_id = int(request.POST.get('productid'))
        product = get_object_or_404(Product, id=product_id)
        serialized_obj = serializers.serialize('python', [product, ])
        return JsonResponse(serialized_obj, safe=False)
    else:
        all_product = Product.products.all()
        paginator = Paginator(all_product, 6)
        page_number = request.GET.get('page')
        products = paginator.get_page(page_number)

    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            new_comment = comment_form.save(commit=False)
            new_comment.post = product
            new_comment.author = request.user
            comment_form.save()
            return HttpResponseRedirect(request.path_info)

    else:
        comment_form = CommentForm()

    return render(request, 'store/products/detail.html', {'product': product, 'form': comment_form})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

def shop_product(request):
    all_product = Product.products.all()
    paginator = Paginator(all_product, 6)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    return render(request, 'store/shop.html', {'products': products})

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary - Stationary Shop{% endblock %}

{% block content %}
<section class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="content">
          <h1 class="page-name">Cart</h1>
          <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">cart</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="page-wrapper">
  <div class="cart shopping">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="block">
            <div class="product-list">
              <form method="post">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Item Name</th>
                      <th>Item Price</th>
                      <th>Quantity</th>
                      <th>Subtotal</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <div id="product-container">
                      
                      {% for item in basket %}
                      {% with product=item.product %}
                      <tr class="product-item" data-index="{{product.id}}">
                        <td class="qq">
                          <div class="product-info">
                            <img class="qq" width="80" src="{{ product.image.url }}" alt="" />
                            <a class="qq" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                          </div>
                        </td>
                        <td class="qq">${{ product.price }}</td>
                        <td class="qq">
                          <div class="product-quantity-slider">
                            <input class="qq" id="select{{ product.id }}" type="text" value="{{ item.qty }}"
                              name="product-quantity">
                          </div>
                        </td>
                        <td class="qq" id="ptotal" data-index="{{product.id}}">${{ item.total_price }}</td>
                        <td class="qq">
                          <a type="button" id="delete-button" data-index="{{product.id}}"
                            class="delete-button product-remove">Remove</a>
                            <br>
                            <br>
                          <a type="button" data-index="{{product.id}}" class="product-update update-button"
                            id="update-button">Update</a>
                        </td>
                      </tr>
                      {% endwith %}
                      {% endfor %}

                    </div>
                  </tbody>
                </table>
                <div class="pull-right">
                  <div>
                    <h5>Sub Total <span id="subtotal">${{basket.get_subtotal_price}}</span></h5>
                    <h5>Delivery $11.50</h5>
                    <h5>Total to Pay <span id="total">${{basket.get_total_price}}</span></h5>
                  </div>
                  <br>
                  <a href="{% url "payment:basket_view" %}" class="btn btn-main">Checkout</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("total").innerHTML = total;
        $('.media[data-index="' + prodid + '"]').remove();
        $("#success-load").load("{{ request.path }} .media-load");
        showSnackbar("Product removed from cart", "#EF1700");
      },
      error: function (xhr, errmsg, err) {
        console.log(err);
        showSnackbar("Error occured", "#DB0F07");
      }
    });
  });

  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    if ($('#select' + prodid).val() > 0) {
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_update" %}',
        data: {
          productid: $(this).data('index'),
          productqty: $('#select' + prodid).val(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("total").innerHTML = total;
          document.querySelector('#ptotal[data-index="' + prodid + '"]').innerHTML = json.ptotal
          $("#success-load").load("{{ request.path }} .media-load");
          showSnackbar("Product updated", "#65C3E5");
        },
        error: function (xhr, errmsg, err) {
          console.log(err);
        }
      });
    } else {
      console.log("Change Quantity")
    }
  });
</script>
{% endblock %}