account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import TemplateView

from . import views
from .forms import PwdResetConfirmForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('password_reset/', views.password_reset_request, name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name='account/user/delete_confirm.html'), name='delete_confirm'),
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

handler404 = "account.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('add/', views.add, name='add')
]

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.basket_view, name='basket_view'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('error/', views.error_view, name='error'),
    path('webhook/', views.stripe_webhook),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_product'),
    path('store/about', views.about, name='about'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/', views.shop_product, name='shop')
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/defaults.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

store/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    text = forms.CharField(label="Enter Comment", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'text', 'id': 'form-comment'}))

    class Meta:
        model = Comment
        fields = ['text']

store/views.py
from django.core import serializers
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render

from .forms import CommentForm
from .models import Category, Product


def about(request):
    return render(request, 'store/about.html')


def all_products(request):
    # Toggle product
    if request.method == "POST":
        product_id = int(request.POST.get('productid'))
        product = get_object_or_404(Product, id=product_id)
        serialized_obj = serializers.serialize('python', [product, ])
        return JsonResponse(serialized_obj, safe=False)
    else:
        all_product = Product.products.all()
        paginator = Paginator(all_product, 6)
        page_number = request.GET.get('page')
        products = paginator.get_page(page_number)

    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            new_comment = comment_form.save(commit=False)
            new_comment.post = product
            new_comment.author = request.user
            comment_form.save()
            return HttpResponseRedirect(request.path_info)

    else:
        comment_form = CommentForm()

    return render(request, 'store/products/detail.html', {'product': product, 'form': comment_form})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

def shop_product(request):
    all_product = Product.products.all()
    paginator = Paginator(all_product, 6)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    return render(request, 'store/shop.html', {'products': products})

templates/store/about.html
{% extends "./base.html" %}
{% load static %}
{% block title %}About - Stationary Shop{% endblock %}

{% block content %}
<div class="d-flex h-100 text-center">
    <section class="py-5 text-center container">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <main class="px-3 col-lg-6 col-md-8 mx-auto pt-5">
                <h1>About Page</h1>
                <p class="lead text-muted">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
                <p class="lead">
                    <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
                </p>
            </main>
        
            <footer class="mt-auto text-white-50">
            <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
            </footer>
        </div> 
    </section>
</div>

{% endblock %}

templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Basic Page Needs
  ================================================== -->
    <meta charset="utf-8">
    <title>{% block title %}Fashion Store - Low Prices in Books & more{% endblock %}</title>

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Construction Html5 Template">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
    <meta name="author" content="Themefisher">
    <meta name="generator" content="Themefisher Constra HTML Template v1.0">

    <!-- {% static 'css/style.css '%} -->
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />

    <!-- Themefisher Icon font -->
    <link rel="stylesheet" href="{% static 'plugins/themefisher-font/style.css' %}">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">

    <!-- Animate css -->
    <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/slick/slick-theme.css' %}">

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

</head>

<style>
    .img-logo {
        width: 14rem;
    }
</style>

<body id="body">
    <!-- Navigation-->
    <!-- Start Top Header Bar -->
    <section class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12 col-sm-4">
                    <div class="contact-number">
                        <i class="tf-ion-ios-telephone"></i>
                        <span>0129- 12323-123123</span>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12 col-sm-4">
                    <!-- Site Logo -->
                    <div class="logo text-center">
                        <a href="{% url 'store:all_product' %}">
                            <!-- replace logo here -->
                            <img class="img-logo" src="{% static 'images/logos.png' %}">
                        </a>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12 col-sm-4">
                    <!-- Cart -->
                    <ul class="top-menu text-right list-inline">
                        <li class="dropdown cart-nav dropdown-slide">
                            <a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
                                    class="tf-ion-android-cart"></i>Cart</a>
                            <div class="dropdown-menu cart-dropdown" id="success-load">
                                <div class="media-load">
                                    {% for item in basket %}
                                    {% with product=item.product %}
                                    <!-- Cart Item -->
                                    <div class="media" data-index="{{ product.id }}">
                                        <a class="pull-left" href="{{ product.get_absolute_url }}">
                                            <img class="media-object" src="{{ product.image.url }}" alt="image" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a
                                                    href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
                                            <div class="cart-price">
                                                <span>{{ item.qty }} x</span>
                                                <span>{{ item.price }}</span>
                                            </div>
                                            <h5><strong>${{ product.price }}</strong></h5>
                                        </div>
                                    </div><!-- / Cart Item -->
                                    {% endwith %}
                                    {% endfor %}
                                    <div class="cart-summary">
                                        <span>Total</span>
                                        <span id="total-price">${{ basket_total_price }}</span>
                                    </div>
                                    <ul class="text-center cart-buttons">
                                        <li><a href="{% url 'basket:basket_summary' %}" class="btn btn-small">View
                                                Cart</a></li>
                                        <li><a href="{% url 'payment:basket_view' %}"
                                                class="btn btn-small btn-solid-border">Checkout</a></li>
                                    </ul>
                                </div>
                            </div>

                        </li><!-- / Cart -->

                        {% if user.is_authenticated %}
                        <a href="{% url 'account:dashboard' %}" class="btn btn-main btn-icon btn-small"><i
                                class="tf-ion-android-contact"></i> Dashboard</a>

                        {% else %}
                        <a href="{% url 'account:login' %}" class="btn btn-main btn-small">Sign In</a>

                        {% endif %}

                    </ul><!-- / .nav .navbar-nav .navbar-right -->
                </div>
            </div>
        </div>
    </section><!-- End Top Header Bar -->


    <!-- Main Menu Section -->
    <section class="menu">
        <nav class="navbar navigation">
            <div class="container">
                <div class="navbar-header">
                    <h2 class="menu-title">Main Menu</h2>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div><!-- / .navbar-header -->

                <!-- Navbar Links -->
                <div id="navbar" class="navbar-collapse collapse text-center">
                    <ul class="nav navbar-nav">

                        <!-- Home -->
                        <li class="dropdown ">
                            <a href="{% url 'store:all_product' %}">Home</a>
                        </li><!-- / Home -->

                        {% if user.is_authenticated %}
                        <li class="dropdown ">
                            <a href="{% url 'wishlist:list' %}">My Wishlist</a>
                        </li><!-- / Home -->
                        {% endif %}

                        <!-- Home -->
                        <li class="dropdown ">
                            <a href="{% url 'store:shop' %}">Shop</a>
                        </li><!-- / Home -->

                        <!-- Shop -->
                        <li class="dropdown dropdown-slide">
                            <a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                                data-delay="350" role="button" aria-haspopup="true" aria-expanded="false">Clothes <span
                                    class="tf-ion-ios-arrow-down"></span></a>
                            <ul class="dropdown-menu">
                                {% for c in categories %}
                                <li><a href="{{ c.get_absolute_url }}">{{ c.name|title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li><!-- / Blog -->

                        <!-- Blog -->
                        <li class="dropdown dropdown-slide">
                            <a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                                data-delay="350" role="button" aria-haspopup="true" aria-expanded="false">Accessories <span
                                    class="tf-ion-ios-arrow-down"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Category 1</a></li>
                                <li><a href="#">Category 2</a></li>
                                <li><a href="#">Category 3</a></li>
                            </ul>
                        </li><!-- / Blog -->

                        <!-- Blog -->
                        <li class="dropdown dropdown-slide">
                            <a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                                data-delay="350" role="button" aria-haspopup="true" aria-expanded="false">Jewellery <span
                                    class="tf-ion-ios-arrow-down"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Category 1</a></li>
                                <li><a href="#">Category 2</a></li>
                                <li><a href="#">Category 3</a></li>
                            </ul>
                        </li><!-- / Blog -->
                        
                    </ul><!-- / .nav .navbar-nav -->

                </div>
                <!--/.navbar-collapse -->
            </div><!-- / .container -->
        </nav>
    </section>
    <!-- Content-->
    <div id="content">{% block content %} {% endblock %}</div>
    <!-- Footer-->
    <footer class="footer section text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="social-media">
                        <li>
                            <a href="https://www.facebook.com/themefisher">
                                <i class="tf-ion-social-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/themefisher">
                                <i class="tf-ion-social-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.twitter.com/themefisher">
                                <i class="tf-ion-social-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.pinterest.com/themefisher/">
                                <i class="tf-ion-social-pinterest"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="footer-menu text-uppercase">
                        <li>
                            <a href="contact.html">CONTACT</a>
                        </li>
                        <li>
                            <a href="shop.html">SHOP</a>
                        </li>
                        <li>
                            <a href="pricing.html">Pricing</a>
                        </li>
                        <li>
                            <a href="contact.html">PRIVACY POLICY</a>
                        </li>
                    </ul>
                    <p class="copyright-text">Copyright &copy;2021, Designed &amp; Developed by <a
                            href="https://themefisher.com/">Themefisher</a>, Backend system & integration by <a class="button"
                            href="https://gitlab.com/pratamailham206">Ilham Pratama</a></p>
                </div>
            </div>
        </div>
        <div id="snackbar">Some text some message..</div>

    </footer>
</body>

<script src="{% static 'js/snackbar.js' %}" data-rel-js></script>
<!-- Bootstrap 3.1 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Bootstrap Touchpin -->
<script src="{% static 'plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' %}"></script>
<!-- Instagram Feed Js -->
<script src="{% static 'plugins/instafeed/instafeed.min.js' %}"></script>
<!-- Video Lightbox Plugin -->
<script src="{% static 'plugins/ekko-lightbox/dist/ekko-lightbox.min.js' %}"></script>
<!-- Count Down Js -->
<script src="{% static 'plugins/syo-timer/build/jquery.syotimer.min.js' %}"></script>

<!-- slick Carousel -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<script src="{% static 'plugins/slick/slick-animation.min.js' %}"></script>

<!-- Main Js File -->
<script src="{% static 'js/script.js' %}"></script>

</html>