basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

handler404 = "account.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('add/', views.add, name='add')
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_product'),
    path('store/about', views.about, name='about'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/', views.shop_product, name='shop')
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/defaults.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

store/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    text = forms.CharField(label="Enter Comment", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'text', 'id': 'form-comment'}))

    class Meta:
        model = Comment
        fields = ['text']

store/views.py
from django.core import serializers
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render

from .forms import CommentForm
from .models import Category, Product


def about(request):
    return render(request, 'store/about.html')


def all_products(request):
    # Toggle product
    if request.method == "POST":
        product_id = int(request.POST.get('productid'))
        product = get_object_or_404(Product, id=product_id)
        serialized_obj = serializers.serialize('python', [product, ])
        return JsonResponse(serialized_obj, safe=False)
    else:
        all_product = Product.products.all()
        paginator = Paginator(all_product, 6)
        page_number = request.GET.get('page')
        products = paginator.get_page(page_number)

    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            new_comment = comment_form.save(commit=False)
            new_comment.post = product
            new_comment.author = request.user
            comment_form.save()
            return HttpResponseRedirect(request.path_info)

    else:
        comment_form = CommentForm()

    return render(request, 'store/products/detail.html', {'product': product, 'form': comment_form})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

def shop_product(request):
    all_product = Product.products.all()
    paginator = Paginator(all_product, 6)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    return render(request, 'store/shop.html', {'products': products})

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}{{ category.name }} - Fashion Shop{% endblock %}

{% block content %}

<style>
  .img-responsive {
    max-height: 60vh;
    object-fit: cover;
  }

  .img-responsive-modal {
    max-height: 75vh;
    object-fit: cover;
  }

  @media only screen and (max-width: 1280px) {
    .img-responsive {
      max-height: 50vh;
      object-fit: cover;
    }
  }

  @media only screen and (max-width: 768px) {

    /* For mobile phones: */
    .img-responsive {
      max-height: 100%;
      object-fit: cover;
    }
  }
</style>

<section class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="content">
          <h1 class="page-name">{{ category.name }}</h1>
          <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">{{ category.name }}</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="products section">
  <div class="container">
    <div class="row">

      {% if not products %}
      <div class="col-12">
        <div class="title text-center">
          <h4>There are currently no products active</h4>
        </div>
      </div>

      {% else %}
      {% for product in products %}
      <div class="col-md-4">
        <div class="product-item">
          <div class="product-thumb">
            <span class="bage">Sale</span>
            <img class="img-responsive" src="{{ product.image.url }}" alt="product-img" />
            <div class="preview-meta">
              <ul>
                <li>
                  <span data-toggle="modal" data-target="#product-modal" id="toggle-product"
                    data-index="{{ product.id }}">
                    <i class="tf-ion-ios-search-strong"></i>
                  </span>
                </li>
                {% if user.is_authenticated %}
                <li>
                  <a data-index="{{ product.id }}" class="add-wish"><i class="tf-ion-ios-heart"></i></a>
                </li>
                {% endif %}
                <li>
                  <a data-index="{{ product.id }}" class="add-product"><i class="tf-ion-android-cart"></i></a>
                </li>
              </ul>
            </div>
          </div>
          <div class="product-content">
            <h4><a href="product-single.html">{{ product.title }}</a></h4>
            <p class="price">${{ product.price }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}

      <div class="modal product-modal fade" id="product-modal">
        <div class="modal-dialog " role="document">
          <div class="modal-content">
            <div class="modal-body">
              <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                  <div class="modal-image">
                    <img id="product-image" class="img-responsive-modal"
                      src="{% static 'images/modal-product.jpg' %}" alt="product-img" />
                  </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                  <div class="product-short-details">
                    <h2 id="product-title" class="product-title">GM Pendant, Basalt Grey</h2>
                    <p id="product-price" class="product-price">$200</p>
                    <p id="product-description" class="product-short-description">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem iusto nihil cum. Illo laborum
                      numquam rem aut officia dicta cumque.
                    </p>
                    <a data-index="" href="" class="btn btn-main add-product">Add To Cart</a>
                    <a id="absolute-url" href="" class="btn btn-transparent">View Product Details</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.modal -->

    </div>
  </div>
</section>

<script>
  $(document).on('click', '#toggle-product', function (e) {
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "store:all_product" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        var item = json[0];
        var product = json[0].fields;
        var URL = 'https://pratamailham.pythonanywhere.com/';
        document.getElementById("product-title").innerHTML = product.title;
        document.getElementById("product-price").innerHTML = product.price;
        document.getElementById("product-description").innerHTML = product.description;
        $('#product-image').attr('src', URL + 'media/' + product.image);
        $('#absolute-url').attr('href', URL + 'item/' + product.slug);
        $('.product-short-details .add-product').attr('data-index', item.pk);
      },
      error: function (xhr, errmsg, err) {
        console.log(err);
      }
    });
  });
  $(document).on('click', '.add-product', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: prodid,
        productqty: 1,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $("#success-load").load("{{ request.path }} .media-load");
        showSnackbar("Product added to Cart", "#4BCA81");
      },
      error: function (xhr, errmsg, err) {
        console.log(err)
      }
    });
  });
  $(document).on('click', '.add-wish', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "wishlist:add" %}',
      data: {
        product_id: prodid,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        console.log(json);
        showSnackbar("Product added to Wish", "#F260B5");
      },
      error: function (xhr, errmsg, err) {
        console.log(err)
      }
    });
  });
</script>
{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}{{ product.title }} - Stationary Shop{% endblock %}

{% block content %}

<section class="single-product">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="shop.html">Shop</a></li>
                    <li class="active">Single Product</li>
                </ol>
            </div>
            <div class="col-md-6">
                <ol class="product-pagination text-right">
                    <li><a href=""><i class="tf-ion-ios-arrow-left"></i> Next </a></li>
                    <li><a href="">Preview <i class="tf-ion-ios-arrow-right"></i></a></li>
                </ol>
            </div>
        </div>
        <div class="row mt-20">
            <div class="col-md-5">
                <div class="single-product-slider">
                    <div id='carousel-custom' class='carousel slide' data-ride='carousel'>
                        <div class='carousel-outer'>
                            <!-- me art lab slider -->
                            <div class='carousel-inner '>
                                <div class='item active'>
                                    <img src='{{ product.image.url }}' alt=''
                                        data-zoom-image="{{ product.image.url }}" />
                                </div>
                            </div>

                            <!-- sag sol -->
                            <a class='left carousel-control' href='#carousel-custom' data-slide='prev'>
                                <i class="tf-ion-ios-arrow-left"></i>
                            </a>
                            <a class='right carousel-control' href='#carousel-custom' data-slide='next'>
                                <i class="tf-ion-ios-arrow-right"></i>
                            </a>
                        </div>

                        <!-- thumb -->
                        <ol class='carousel-indicators mCustomScrollbar meartlab'>
                            <li data-target='#carousel-custom' data-slide-to='0' class='active'>
                                <img src='{{ product.image.url }}' alt='' />
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="single-product-details">
                    <h2>{{ product.title }}</h2>
                    <p class="product-price">$300</p>

                    <p class="product-description mt-20">
                        {{ product.description }}.
                    </p>
                    <p>{{ product.description }}.</p>

                    <div class="product-quantity">
                        <span>Quantity:</span>
                        <div class="product-quantity-slider">
                            <input id="select" type="text" value="1" name="product-quantity">
                        </div>
                    </div>
                    <div class="product-category">
                        <span>Categories:</span>
                        <ul>
                            <li><a href="product-single.html">{{ product.category }}</a></li>
                        </ul>
                    </div>
                    <button id="add-button" value="{{ product.id }}" class="btn btn-main mt-20" type="button">Add to
                        cart</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="tabCommon mt-20">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#details" aria-expanded="true">Details</a></li>
                        <li class=""><a data-toggle="tab" href="#reviews" aria-expanded="false">Reviews ({{ product.comments.count }})</a></li>
                    </ul>
                    <div class="tab-content patternbg">
                        <div id="details" class="tab-pane fade active in">
                            <h4>Product Description</h4>
                            <p>{{ product.description }}</p>
                            <p>{{ product.description }}</p>
                        </div>
                        <div id="reviews" class="tab-pane fade">
                            <div class="post-comments">
                                <ul class="media-list comments-list m-bot-50 clearlist">
                                    
                                    <!-- Comment Item start-->
                                    {% for comment in product.comments.all %}
                                    <li class="media">

                                        <a class="pull-left" href="#!">
                                            <img class="media-object comment-avatar" src="{{ comment.author.profile.url }}"
                                                alt="" width="50" height="50" />
                                        </a>

                                        <div class="media-body">
                                            <div class="comment-info">
                                                <h4 class="comment-author">
                                                    <a href="#!">{{ comment.author }}</a>

                                                </h4>
                                                <time datetime="2013-04-06T13:53">{{ comment.created_date }}</time>
                                                <a class="comment-button" href="#!"><i
                                                        class="tf-ion-chatbubbles"></i>Reply</a>
                                            </div>

                                            <p>
                                                {{ comment.text }}
                                            </p>
                                        </div>

                                    </li>
                                    {% empty %}
                                    <h4>No Comments yet</h4>
                                    
                                    {% endfor %}
                                    {% if user.is_authenticated %}
                                    <form class="text-left clearfix" method="post">
                                        {% csrf_token %}

                                        {% if form.is_valid %}
                                        <div class="alert alert-success alert-common" role="alert"><i class="tf-ion-thumbsup"></i>
                                            Details successfully updated!
                                        </div>

                                        {% endif %}

                                        {% if form.errors %}
                                        <div class="alert alert-danger alert-common" role="alert"><i class="tf-ion-close-circled"></i>Error: Please try again!</div>
                                        {% endif %}
                
                                        <div class="form-group">
                                            {{ form.text }}
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-main text-center">Add Comment</button>
                                        </div>
                                    </form>
                                    {% endif %}
                                    <!-- End Comment Item -->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).on('click', '#add-button', function (e) {
        var value = $('#select').val();
        if (value > 0) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: value,
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    $("#success-load").load("{{ request.path }} .media-load");
                    showSnackbar("Product added to Cart", "#4BCA81");
                },
                error: function (xhr, errmsg, err) {
                    console.log(err)
                }
            });
        } else {
            console.log("Please change quantity");
        }
    });
</script>

{% endblock %}

templates/store/products/product.html
{% for item in basket %}
{% with product=item.product %}
<!-- Cart Item -->
<div class="media">
    <a class="pull-left" href="{{ product.get_absolute_url }}">
        <img class="media-object" src="{{ product.image.url }}" alt="image" />
    </a>
    <div class="media-body">
        <h4 class="media-heading"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
        <div class="cart-price">
            <span>{{ item.qty }} x</span>
            <span>{{ item.price }}</span>
        </div>
        <h5><strong>${{ product.price }}</strong></h5>
    </div>
</div><!-- / Cart Item -->
{% endwith %}
{% endfor %}